### ISSUE TITLE
Android can't find alfresco-mobile-android-client-api:1.5'

### ISSUE THREAD

**Issue by letroll** [Alfresco/alfresco-android-app#436]
Hello, 

When gradle sync end Android Studio show the following message:

Error:Failed to resolve: org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.5

**Comment by jmpascal** [comment]
Hello,

Currently we are on the final stage of releasing both a new version of Alfresco Android SDK & Alfresco Android APP. Both source code are up to date in their respective master branch but artifacts are still not available in our Maven repositories. That's why you have the current issue with SDK dependencies.

To solve this issue you need to build the [Alfresco Android SDK](https://github.com/Alfresco/alfresco-android-sdk) and install it in your local maven repository.

We understand it's a little bit frustrated but generally our release preparation phase is not that long ^^

Hope it helps.

**Comment by letroll** [comment]
thanks for the explanation

**Comment by flaviosuardi** [comment]
Hello,

with version 1.8.1 I have this error
``Failed to resolve: org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.5``
when gradle sync.

**Comment by shikoko** [comment]
Hello @flaviosuardi,

Have you built and installed the [Alfresco Android SDK](https://github.com/Alfresco/alfresco-android-sdk) on your local maven repository as stated above?

**Comment by flaviosuardi** [comment]
Hi @shikoko,

yes, I solved building `alfresco-mobile-android-client-api:1.5` with maven and imported the jars generated in android studio project.

Thanks.
